version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    networks:
     - bot_network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    restart: always
    depends_on:
     - bot
    networks:
     - bot_network
    ports:
     - "443:443"
    environment:
      PROXY_ONE: http://bot:5000
      PROXY_TWO: https://script.google.com/macros/s/AKfycbzdhpV0t5g5HxwqtAKTIc1U0BRTbEIXPNsrjCRkww/exec

networks:
 bot_network:
